In [2]:
import pickle 
import numpy as np


In [15]:
X = pickle.load(open('A.pkl','rb'))



In [27]:
y = pickle.load(open('B.pkl','rb'))

In [17]:
arc_lengths = pickle.load(open('arcLengths.pkl','rb'))

In [18]:
arc_lengths = np.array(arc_lengths)
arc_lengths

array([ 596.        ,  596.        ,  571.98275506,  596.        ,
        511.66399407,  670.46803617,  596.        ,  596.        ,
        511.56348908,  596.        ,  596.82842708,  596.        ,
        596.        ,  596.        ,  596.        ,  606.48528123,
        596.        ,  397.92387998,  590.1665206 ,  596.        ,
        596.        ,  608.72792184, 1404.62445176,  596.82842708,
        596.        ,  603.31370831,  764.10764527,  596.        ,
        596.        ,  596.        ,  682.12489045,  596.82842708,
        596.        ,  596.        ,  914.24978077,  596.        ,
       2108.76065838,  596.82842708,  614.97056246,  596.        ,
        596.        ,  600.82842708,  596.        ,  610.62741661,
        596.        ,  612.87005723,  596.        ,  596.        ,
        596.        ,  596.        ,  600.24264061,  385.29646325,
        597.65685415,  596.        ,  467.82337475,  596.        ,
        669.1959579 ,  682.49242103,  678.52691138,  596.     

In [19]:
arc_lengths.shape
arc_lengths = arc_lengths.reshape(-1,1)
arc_lengths = (arc_lengths-arc_lengths.min())/(arc_lengths.max()-arc_lengths.min())
arc_lengths

array([[0.08983922],
       [0.08983922],
       [0.08382467],
       [0.08983922],
       [0.06871926],
       [0.10848797],
       [0.08983922],
       [0.08983922],
       [0.06869409],
       [0.08983922],
       [0.09004668],
       [0.08983922],
       [0.08983922],
       [0.08983922],
       [0.08983922],
       [0.09246501],
       [0.08983922],
       [0.04023575],
       [0.08837836],
       [0.08983922],
       [0.08983922],
       [0.09302662],
       [0.29234002],
       [0.09004668],
       [0.08983922],
       [0.09167076],
       [0.13193779],
       [0.08983922],
       [0.08983922],
       [0.08983922],
       [0.11140715],
       [0.09004668],
       [0.08983922],
       [0.08983922],
       [0.16953732],
       [0.08983922],
       [0.46867423],
       [0.09004668],
       [0.09458994],
       [0.08983922],
       [0.08983922],
       [0.09104838],
       [0.08983922],
       [0.0935023 ],
       [0.08983922],
       [0.09406392],
       [0.08983922],
       [0.089

In [20]:
X = X/255.0

In [21]:
X

array([[[[0.04705882, 0.07058824, 0.09019608],
         [0.03137255, 0.05882353, 0.07058824],
         [0.03921569, 0.0745098 , 0.12941176],
         ...,
         [0.37647059, 0.35686275, 0.24313725],
         [0.26666667, 0.25490196, 0.30588235],
         [0.16078431, 0.20784314, 0.38823529]],

        [[0.05490196, 0.10980392, 0.12156863],
         [0.03921569, 0.08235294, 0.10588235],
         [0.04705882, 0.0745098 , 0.13333333],
         ...,
         [0.2627451 , 0.25098039, 0.35294118],
         [0.39215686, 0.38431373, 0.39215686],
         [0.16470588, 0.17647059, 0.27058824]],

        [[0.05882353, 0.09019608, 0.09019608],
         [0.03137255, 0.08627451, 0.10980392],
         [0.04705882, 0.07058824, 0.08627451],
         ...,
         [0.64313725, 0.65490196, 0.70588235],
         [0.65098039, 0.6627451 , 0.72156863],
         [0.10196078, 0.09803922, 0.16078431]],

        ...,

        [[0.0745098 , 0.1372549 , 0.12941176],
         [0.05882353, 0.07058824, 0.0745098 ]

In [22]:
arc_lengths.shape

(932, 1)

In [23]:
from keras.models import Sequential,Model
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, concatenate, Input

In [24]:
input_img = Input(shape=(150,150,3))
x = Conv2D(64, (3,3), activation='relu')(input_img)
x = MaxPooling2D(pool_size=(2,2))(x)
x = Conv2D(64, (3,3), activation='relu')(x)
x = MaxPooling2D(pool_size=(2,2))(x)
x = Flatten()(x)
image_model = Model(inputs=input_img, outputs=x)

input_int = Input(shape=(1,))
y = Dense(128, activation='relu')(input_int)
gal_model = Model(inputs=input_int, outputs=y)

merged = concatenate([image_model.output, gal_model.output])
merged = Dense(128, activation='relu')(merged)
merged = Dense(2, activation='softmax')(merged)

model = Model(inputs=[image_model.input, gal_model.input], outputs=merged)

In [25]:
model.compile(optimizer='adam', loss= 'sparse_categorical_crossentropy', metrics=['accuracy'])

In [28]:
y = np.array(y)
model.fit([X,arc_lengths],y, epochs=10, validation_data=([X,arc_lengths],y))

Epoch 1/10
30/30 [==============================] - 76s 2s/step - loss: 0.9357 - accuracy: 0.6628 - val_loss: 0.3669 - val_accuracy: 0.8165
Epoch 2/10
30/30 [==============================] - 41s 1s/step - loss: 0.3424 - accuracy: 0.8516 - val_loss: 0.2995 - val_accuracy: 0.8916
Epoch 3/10
30/30 [==============================] - 37s 1s/step - loss: 0.2732 - accuracy: 0.9007 - val_loss: 0.3336 - val_accuracy: 0.8530
Epoch 4/10
30/30 [==============================] - 49s 2s/step - loss: 0.2349 - accuracy: 0.8909 - val_loss: 0.4697 - val_accuracy: 0.8101
Epoch 5/10
30/30 [==============================] - 36s 1s/step - loss: 0.2111 - accuracy: 0.9272 - val_loss: 0.0794 - val_accuracy: 0.9721
Epoch 6/10
30/30 [==============================] - 37s 1s/step - loss: 0.0935 - accuracy: 0.9753 - val_loss: 0.0413 - val_accuracy: 0.9893
Epoch 7/10
30/30 [==============================] - 40s 1s/step - loss: 0.0598 - accuracy: 0.9786 - val_loss: 0.0262 - val_accuracy: 0.9925
Epoch 8/10
30/30 [==

In [29]:
model.save('64x2-CNN_impure_gal_2.model')

INFO:tensorflow:Assets written to: 64x2-CNN_impure_gal_2.model\assets
