In [21]:
import pickle
import numpy as np

In [35]:
X = pickle.load(open('A.pkl','rb'))
y = pickle.load(open('B.pkl','rb'))
via_intensity = pickle.load(open('intensity.pkl','rb'))

In [36]:
via_intensity = np.array(via_intensity)

y

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,

In [37]:
y

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,

In [24]:
X = X/255.0 #feature scaling

In [25]:
X

array([[[[0.00392157, 0.04313725, 0.1372549 ],
         [0.00784314, 0.03921569, 0.11764706],
         [0.00784314, 0.03529412, 0.10980392],
         ...,
         [0.        , 0.01960784, 0.03137255],
         [0.00392157, 0.01960784, 0.03921569],
         [0.        , 0.02352941, 0.05098039]],

        [[0.        , 0.03529412, 0.09019608],
         [0.01568627, 0.05098039, 0.12941176],
         [0.00784314, 0.03921569, 0.11764706],
         ...,
         [0.        , 0.01568627, 0.02745098],
         [0.00392157, 0.02352941, 0.04313725],
         [0.        , 0.03529412, 0.0627451 ]],

        [[0.00392157, 0.04313725, 0.05882353],
         [0.        , 0.03921569, 0.11372549],
         [0.01568627, 0.05882353, 0.14117647],
         ...,
         [0.        , 0.01568627, 0.02745098],
         [0.01176471, 0.04313725, 0.0627451 ],
         [0.00784314, 0.05490196, 0.07843137]],

        ...,

        [[0.11372549, 0.1372549 , 0.16470588],
         [0.00392157, 0.02745098, 0.05098039]

In [26]:
X.shape

(932, 150, 150, 3)

In [38]:
scaled_intensity = via_intensity/np.max(via_intensity)
scaled_intensity

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.05442177, 0.06802721, 0.02040816, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.05442177, 0.08163265, 0.05442177, ..., 0.00680272, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [29]:
from keras.models import Sequential,Model
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, concatenate, Input

In [9]:
# image_model = Sequential()

# image_model.add(Conv2D(64, (3,3), activation='relu'))
# image_model.add(MaxPooling2D(pool_size=(2,2)))

# image_model.add(Conv2D(64, (3,3), activation='relu'))
# image_model.add(MaxPooling2D(pool_size=(2,2)))

# # image_model.add(Conv2D(128, (3,3), activation='relu'))
# # image_model.add(MaxPooling2D(pool_size=(2,2)))

# image_model.add(Flatten())

# intensity_model = Sequential()
# intensity_model.add(Dense(128, input_shape = (150,),activation='relu'))

# merged = concatenate([image_model.output, intensity_model.output])

# merged = Dense(128, activation='relu')(merged)
# merged = Dense(2, activation='softmax')(merged)

# model = Model(inputs=[image_model.input, intensity_model.input], outputs=merged)
# image_model.add(Dense(128, input_shape = X.shape[1:],activation='relu'))


# image_model.add(Dense(2, activation='softmax'))



In [30]:
input_img = Input(shape=(150,150,3))
x = Conv2D(64, (3,3), activation='relu')(input_img)
x = MaxPooling2D(pool_size=(2,2))(x)
x = Conv2D(64, (3,3), activation='relu')(x)
x = MaxPooling2D(pool_size=(2,2))(x)
x = Flatten()(x)
image_model = Model(inputs=input_img, outputs=x)

input_int = Input(shape=(150,))
y = Dense(128, activation='relu')(input_int)
intensity_model = Model(inputs=input_int, outputs=y)

merged = concatenate([image_model.output, intensity_model.output])
merged = Dense(128, activation='relu')(merged)
merged = Dense(2, activation='softmax')(merged)

model = Model(inputs=[image_model.input, intensity_model.input], outputs=merged)

In [31]:
model.compile(optimizer='adam', loss= 'sparse_categorical_crossentropy', metrics=['accuracy'])

In [39]:
y = np.array(y)
model.fit([X,scaled_intensity],y, epochs=10, validation_data=([X,scaled_intensity],y))

Epoch 1/10
30/30 [==============================] - 74s 2s/step - loss: 404.4893 - accuracy: 0.5068 - val_loss: 0.5225 - val_accuracy: 0.6953
Epoch 2/10
30/30 [==============================] - 54s 2s/step - loss: 0.5225 - accuracy: 0.7267 - val_loss: 0.4106 - val_accuracy: 0.8401
Epoch 3/10
30/30 [==============================] - 59s 2s/step - loss: 0.4671 - accuracy: 0.8117 - val_loss: 0.3578 - val_accuracy: 0.8552
Epoch 4/10
30/30 [==============================] - 59s 2s/step - loss: 0.3461 - accuracy: 0.8469 - val_loss: 0.1964 - val_accuracy: 0.9249
Epoch 5/10
30/30 [==============================] - 47s 2s/step - loss: 0.2070 - accuracy: 0.9201 - val_loss: 0.2100 - val_accuracy: 0.9227
Epoch 6/10
30/30 [==============================] - 43s 1s/step - loss: 0.1587 - accuracy: 0.9454 - val_loss: 0.0713 - val_accuracy: 0.9839
Epoch 7/10
30/30 [==============================] - 46s 2s/step - loss: 0.1180 - accuracy: 0.9625 - val_loss: 0.2390 - val_accuracy: 0.9345
Epoch 8/10
30/30 [

In [40]:
model.save('64x2-CNN_impure_scaled_via.model')

INFO:tensorflow:Assets written to: 64x2-CNN_impure_scaled_via.model\assets
